fix(stylelint,eslint): handle invalid JSON config
This commit guards against a failure condition in user provided input.
Reference:
https://gist.github.com/antonlindstrom/be756af0eff8d58971a11ec5598eb422

diff --git a/eslint/eslint-tap b/eslint/eslint-tap
--- a/eslint/eslint-tap
+++ b/eslint/eslint-tap
@@ -22,6 +22,12 @@ main() {
 		return 7
 	fi
 
+	if ! jq -re '.' "${config_file}" 2> "${output}" > /dev/null; then
+		echo "ERROR: ${config_file} is not valid JSON"
+		cat "${output}"
+		return 1
+	fi
+
 	echo '~~~ Preparing configuration'
 
 	local -a args=(-c "${config_file}" -f json --output-file "${output}")
diff --git a/stylelint/stylelint-tap b/stylelint/stylelint-tap
--- a/stylelint/stylelint-tap
+++ b/stylelint/stylelint-tap
@@ -15,6 +15,12 @@ main() {
 	if [ -f "${config_file}" ]; then
 		echo 'INFO: using custom config.json'
 		args+=("--config" "../${config_file}")
+
+		if ! jq -re '.' "${config_file}" 2> "${output}" > /dev/null; then
+			echo 'ERROR: custom config.json is not valid JSON'
+			cat "${output}"
+			return 1
+		fi
 	else
 		echo 'INFO: no custom config.json found; using standard config.'
 		args+=("--config" "../defaults/config.json")
