feat(*): hide blacklisted checks (#26)
This commit uses a dynamic pipeline to only include the whitelist checks
or all if no whitelist configured. This should speed up all check runs
and save money on compute resources.

diff --git a/test/stubs/bin/buildkite-agent b/test/stubs/bin/buildkite-agent
--- a/test/stubs/bin/buildkite-agent
+++ b/test/stubs/bin/buildkite-agent
@@ -24,6 +24,17 @@ metadata_command() {
 	esac
 }
 
+pipeline_command() {
+	case "${1:-}" in
+		upload)
+			metadata_command set pipeline "$(cat)"
+			;;
+		*)
+			echo "Cannot handle $*" 1>&2
+			return 1
+	esac
+}
+
 main() {
 	case "${1:-}" in
 		meta-data)
@@ -32,6 +43,10 @@ main() {
 			;;
 		reset)
 			rm -f "${BUILDKITE_AGENT_METADIR}/"*
+			;;
+		pipeline)
+			shift
+			pipeline_command "$@"
 			;;
 		*)
 			echo "Cannot handle $*" 1>&2
