chore(*): pass shellcheck

diff --git a/test/stubs/bin/git b/test/stubs/bin/git
--- a/test/stubs/bin/git
+++ b/test/stubs/bin/git
@@ -8,9 +8,11 @@ clone_command() {
 		return 1
 	fi
 
-	local org="$(echo "${2}" | cut -d '/' -f 4)"
-	local name="$(echo "${2}" | cut -d '/' -f 5 | cut -d '.' -f 1)"
-	local repo="${org}/${name}"
+	local org name repo
+
+	org="$(echo "${2}" | cut -d '/' -f 4)"
+	name="$(echo "${2}" | cut -d '/' -f 5 | cut -d '.' -f 1)"
+	repo="${org}/${name}"
 
 	if [ -z "${repo}" ]; then
 		echo "Bad repo: ${2}" 1>&2
@@ -27,7 +29,7 @@ clone_command() {
 
 remote_command() {
 	if [ $# -ne 3 ]; then
-		echo "Cannot stub git remote: $@" 1>&2
+		echo "Cannot stub git remote: $*" 1>&2
 		return 1
 	elif [ ! -d .git ]; then
 		echo "No git repo in ${PWD}" 1>&2
@@ -38,9 +40,11 @@ remote_command() {
 			return 1
 		fi
 
-		local org="$(echo "${3}" | cut -d '/' -f 4)"
-		local name="$(echo "${3}" | cut -d '/' -f 5 | cut -d '.' -f 1)"
-		local repo="${org}/${name}"
+		local org name repo
+
+		org="$(echo "${3}" | cut -d '/' -f 4)"
+		name="$(echo "${3}" | cut -d '/' -f 5 | cut -d '.' -f 1)"
+		repo="${org}/${name}"
 
 		if [ -z "${repo}" ]; then
 			echo "Bad repo: ${3}" 1>&2
@@ -53,7 +57,7 @@ remote_command() {
 			return 0
 		fi
 	else
-		echo "Cannot stub git remote: $@" 1>&2
+		echo "Cannot stub git remote: $*" 1>&2
 		return 1
 	fi
 }
@@ -61,7 +65,7 @@ remote_command() {
 fetch_command() {
 	shift 2
 	if [ $# -ne 2 ]; then
-		echo "Cannot stub fetch: $@" 1>&2
+		echo "Cannot stub fetch: $*" 1>&2
 		return 1
 	else
 		echo "${2}" > .git/branch
@@ -70,15 +74,15 @@ fetch_command() {
 }
 
 checkout_command() {
-	local OPTIND
-
 	if [ "${1}" != '-f' ]; then
 		echo "Unexpected git checkout option: ${1}" 1>&2
 		return 1
 	else
-		local repo="$(cat .git/repo)"
-		local branch="$(cat .git/branch)"
-		local fixture="${FIXTURE_DIR}/${repo}/${branch}"
+		local repo branch fixture
+
+		repo="$(cat .git/repo)"
+		branch="$(cat .git/branch)"
+		fixture="${FIXTURE_DIR}/${repo}/${branch}"
 
 		if [ -z "${repo:-}" ] || [ -z "${branch:-}" ]; then
 			echo "No repo/branch stub configured" 1>&2
@@ -100,7 +104,7 @@ pull_command() {
 		echo "No git branch in ${PWD}" 1>&2
 		return 1
 	elif [ $# -ne 2 ]; then
-		echo "Cannot stub pull ${@}" 1>&2
+		echo "Cannot stub pull $*" 1>&2
 		return 1
 	elif [ "${1}" != 'origin' ]; then
 		echo "must pull from origin" 1>&2
@@ -170,7 +174,7 @@ main() {
 			remote_command "$@"
 			;;
 		*)
-			echo "Cannot stub git command: $@" 1>&2
+			echo "Cannot stub git command: $*" 1>&2
 			return 1
 	esac
 }
